v0.3.99: extended .gitlab-ci.yml-template to allow projects with optional unit tests
useful for playground project type (without a tests/TESTS_FOLDER folder in the project/repository root folder)

M  .gitignore
M  .gitlab-ci.yml
M  CONTRIBUTING.rst
M  LICENSE.md
M  README.md
M  SECURITY.md
M  aedev/project_tpls/__init__.py
M  "aedev/project_tpls/templates/SkpTyp-playground_tests/fSt-test_{portion_name or project_name}.py"
M  aedev/project_tpls/templates/fSt-PutMar-.gitlab-ci.yml
M  dev_requirements.txt
M  pyproject.toml
M  setup.py
M  tests/conftest.py
M  tests/requirements.txt

diff --git a/aedev/project_tpls/templates/fSt-PutMar-.gitlab-ci.yml b/aedev/project_tpls/templates/fSt-PutMar-.gitlab-ci.yml
--- a/aedev/project_tpls/templates/fSt-PutMar-.gitlab-ci.yml
+++ b/aedev/project_tpls/templates/fSt-PutMar-.gitlab-ci.yml
@@ -28,16 +28,23 @@ integrity:
     - >
       pip install --upgrade --force-reinstall --uploaded-prior-to={PYPI_COOLDOWN_PERIOD}
       -r {frozen_req_file_path()}
-      -r {frozen_req_file_path(TESTS_FOLDER + "/" + REQ_FILE_NAME)}
+      {"-r " + frozen_req_file_path(_f_) if os_path_isfile(_f_ := TESTS_FOLDER + "/" + REQ_FILE_NAME) else ""}
     {"- pip install --upgrade --force-reinstall " + " ".join(_c_) if (_c_ := cooldown_excluded_projects) else ""}
   script:
     - pipx run --spec aedev_project_manager project-manager -v check-integrity
+    - |
+      if [ -d tests ]; then
+        test -d htmlcov || {{ echo "CI-ERROR: tests/ exists, but htmlcov/ was not created"; exit 1; }}
+        test -d .pytest_cache || {{ echo "CI-ERROR: tests/ exists, but .pytest_cache/ was not created"; exit 1; }}
+      else
+        mkdir -p htmlcov .pytest_cache
+      fi
   artifacts:
     paths:
       - mypy_report/
       - .pylint/
       - htmlcov/
-      - .pytest_cache
+      - .pytest_cache/
 
 pages:
   stage: deploy
@@ -47,12 +54,15 @@ pages:
   script:
     - ls -l -R
     - mkdir -p public/coverage
-    - mv -f -v htmlcov/* public/coverage
-    - mv -f -v .pytest_cache/coverage.svg public/
-    - mv -f -v mypy_report/lineprecision.txt public/
-    - mv -f -v mypy_report/mypy.svg public/
-    - mv -f -v .pylint/pylint.svg public/
-    - mv -f -v .pylint/pylint.log public/
+    - |
+      if [ -d tests ]; then
+        cp -a -f -v htmlcov/. public/coverage/
+        cp -a -f -v .pytest_cache/coverage.svg public/
+      fi
+    - cp -a -f -v mypy_report/lineprecision.txt public/
+    - cp -a -f -v mypy_report/mypy.svg public/
+    - cp -a -f -v .pylint/pylint.svg public/
+    - cp -a -f -v .pylint/pylint.log public/
   artifacts:
     paths:
       - public
